name: MLflow Project CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12

      - name: Install dependencies
        run: |
          conda env update -f MLProject/conda.yaml

      - name: Run MLflow Project
        run: |
          mlflow run MLProject
