name: MLflow Project CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12
      - name: Install dependencies
        run: |
          conda env update -f MLProject/conda.yaml
      - name: Run MLflow project
        run: |
          mlflow run MLProject
      - name: Upload to Google Drive
        # ...kode upload/atau ganti ke upload ke repo Github (misal pakai actions/upload-artifact)
      - name: Build Docker Model
        run: |
          mlflow models build-docker -m <path_model>
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker Image
        run: docker tag ...
      - name: Push Docker Image
        run: docker push ...
