name: MLflow Project CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12

      - name: Install dependencies
        run: |
          conda env update -f MLProject/conda.yaml

      - name: Run MLflow Project
        run: |
          mlflow run MLProject

      # ====== STEP TAMBAHAN UNTUK ADVANCED ======
      - name: Build Docker Model
        run: |
          # Ganti path model sesuai lokasi hasil run kamu
          MODEL_PATH=$(ls -d mlruns/0/*/artifacts/model | head -n 1)
          echo "Model path: $MODEL_PATH"
          mlflow models build-docker -m $MODEL_PATH -n habibie1798/final-project:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push habibie1798/final-project:latest
