name: MLflow Project CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12

      - name: Install dependencies
        run: conda env update -f conda.yaml

      - name: Run MLflow Project
        run: mlflow run .


      - name: Build Docker Model
        run: |
          mlflow models build-docker -m Workflow-CI/MLProject/mlruns/0/*/artifacts/model -n final_model

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag final_model:latest habibiealrasyid17/final_model:latest

      - name: Push Docker Image
        run: |
          docker push habibiealrasyid17/final_model:latest
