name: Preprocessing CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_Habibiealrasyid17.py

      - name: Upload preprocessed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/namadataset_preprocessing/telco_preprocessed.csv

